host = 'data.usajobs.gov';  
user_agent = 'chrisrmartinez@lewisu.edu';  
auth_key = 'HIsBP7XSYBGCed+lbWZhGYThQAnkwoW7CUJ4X6sKytk='; 

position_titles = [
    'Administrative Assistant',
    'Office Manager',
    'Receptionist',
    'Executive Assistant',
    'Data Entry Clerk',
    'Virtual Assistant',
    'Secretary',
    'File Clerk',
    'Personal Assistant',
    'Accountant',
    'Financial Analyst',
    'Bookkeeper',
    'Auditor',
    'Accounts Payable Clerk',
    'Accounts Receivable Clerk',
    'Budget Analyst',
    'Controller',
    'Tax Specialist',
    'Payroll Coordinator',
    'Chief Financial Officer (CFO)',
    'Loan Officer',
    'Investment Banker',
    'Marketing Manager',
    'Digital Marketing Specialist',
    'Social Media Manager',
    'Brand Manager',
    'Public Relations Specialist',
    'SEO Specialist',
    'Content Creator',
    'Copywriter',
    'Email Marketing Specialist',
    'Media Buyer',
    'Market Research Analyst',
    'Chief Marketing Officer (CMO)',
    'Graphic Designer',
    'Art Director',
    'Illustrator',
    'Animator',
    'UX/UI Designer',
    'Video Editor',
    'Photographer',
    'Fashion Designer',
    'Interior Designer',
    'Creative Director',
    'Business Analyst',
    'Management Consultant',
    'Project Manager',
    'Operations Manager',
    'Chief Executive Officer (CEO)',
    'Chief Operating Officer (COO)',
    'Product Manager',
    'Business Development Manager',
    'Customer Service Representative',
    'Call Center Agent',
    'Client Relations Manager',
    'Help Desk Support',
    'Technical Support Specialist',
    'Customer Success Manager',
    'Teacher',
    'Professor',
    'Tutor',
    'Instructional Designer',
    'Academic Advisor',
    'Training Coordinator',
    'Special Education Teacher',
    'School Administrator',
    'Librarian',
    'Civil Engineer',
    'Mechanical Engineer',
    'Electrical Engineer',
    'Software Engineer',
    'Structural Engineer',
    'Aerospace Engineer',
    'Chemical Engineer',
    'Environmental Engineer',
    'Architect',
    'CAD Technician',
    'Doctor (Physician)',
    'Surgeon',
    'Nurse',
    'Pharmacist',
    'Dentist',
    'Physical Therapist',
    'Medical Assistant',
    'Radiologic Technologist',
    'Veterinarian',
    'Mental Health Counselor',
    'Healthcare Administrator',
    'HR Manager',
    'Recruiter',
    'HR Generalist',
    'HR Coordinator',
    'Talent Acquisition Specialist',
    'Compensation & Benefits Manager',
    'Employee Relations Specialist',
    'Training & Development Manager',
    'Software Developer',
    'IT Support Specialist',
    'Network Engineer',
    'Cybersecurity Analyst',
    'Database Administrator',
    'IT Manager',
    'Systems Analyst',
    'Cloud Engineer',
    'DevOps Engineer',
    'Data Scientist',
    'Chief Technology Officer (CTO)',
    'Lawyer (Attorney)',
    'Paralegal',
    'Legal Assistant',
    'Corporate Counsel',
    'Judge',
    'Legal Analyst',
    'Court Clerk',
    'Factory Worker',
    'Quality Control Inspector',
    'Machinist',
    'Welder',
    'Electrician',
    'Plumber',
    'Carpenter',
    'HVAC Technician',
    'Journalist',
    'Editor',
    'News Anchor',
    'Publicist',
    'Podcaster',
    'Broadcaster',
    'Translator',
    'Sales Associate',
    'Retail Manager',
    'Account Executive',
    'Sales Representative',
    'Business Development Executive',
    'Territory Manager',
    'Customer Success Manager',
    'Scientist',
    'Lab Technician',
    'Chemist',
    'Biologist',
    'Research Associate',
    'Data Analyst',
    'Logistics Coordinator',
    'Supply Chain Manager',
    'Warehouse Supervisor',
    'Procurement Specialist',
    'Distribution Manager',
    'Inventory Analyst',
    'Hotel Manager',
    'Event Planner',
    'Flight Attendant',
    'Chef',
    'Bartender',
    'Concierge',
    'Tour Guide',
    'Police Officer',
    'Security Guard',
    'FBI Agent',
    'Private Investigator',
    'Corrections Officer',
    'Firefighter',
    'Truck Driver',
    'Delivery Driver',
    'Mechanic',
    'Fleet Manager',
    'Automotive Engineer',
    'Social Worker',
    'Community Outreach Coordinator',
    'Fundraiser',
    'Nonprofit Director'
]

government_organizations = [
    'Department of Agriculture',
    'Department of Commerce',
    'Department of Defense',
    'Department of Education',
    'Department of Energy',
    'Department of Health and Human Services',
    'Department of Homeland Security',
    'Department of Housing and Urban Development',
    'Department of the Interior',
    'Department of Justice',
    'Department of Labor',
    'Department of State',
    'Department of Transportation',
    'Department of the Treasury',
    'Department of Veterans Affairs',
    'Environmental Protection Agency',
    'Federal Communications Commission',
    'Federal Trade Commission',
    'General Services Administration',
    'National Aeronautics and Space Administration',
    'National Science Foundation',
    'Nuclear Regulatory Commission',
    'Office of Personnel Management',
    'Small Business Administration',
    'Social Security Administration',
    'United States Agency for International Development'
]

